<div data-mage-init='<?php echo $this->getRequiredScripts();?>' class="devbar__item js-devbar__item <?php echo $block->getCssClass();?>">
    <div class="devbar__button">
        <a href="#" class="devbar__button-link js-devbar__button-link">
            <?php echo $block->getButtonTitle();?>
        </a>
    </div>
    
    <div class="devbar__panel js-devbar__panel">
        <div class="devbar__panel-inner">
            <div class="devbar__panel-head">
                <h4 class="devbar__panel-title">
                    <?php echo $block->getTitle();?>
                </h4>
            </div>
    
            <div class="devbar__panel-body">
                <?php echo $block->getContent(); ?>
            </div>
        </div>
    </div>
</div>