<?php $_item = $block->getItem();?>
<?php $_childrenHtml = $block->getChildrenHtml(); ?>

<li class="devbar__list-item">
    <div class="devbar__info">
        <?php if($_childrenHtml): ?>
            <a href="#" class="devbar__toggle js-devbar__toggle"><span><?php echo $block->getName(); ?></span></a>
        <?php else: ?>
            <span class=""><?php echo $block->getName(); ?></span>
        <?php endif; ?>
        <?php if($extras = $block->getExtras()): ?>
            <span class="devbar__extras">
                <?php echo " | " . implode(" | ", $extras);?>
            </span>
        <?php endif;?>
        <a href="#" <?php echo $block->getOutputAttributes();?> class="devbar__highlight-toggle js-devbar__highlight-toggle"><?php echo __('Highlight') ?></a>
    </div>
    <?php echo $_childrenHtml; ?>
</li>