<?php $_item = $block->getItem();?>
<?php $_childrenHtml = $block->getChildrenHtml(); ?>

<li class="developertoolbar__list-item">    
    <?php if($_childrenHtml): ?>
        <a href="#" class="developertoolbar__toggle js-developertoolbar__toggle">
    <?php endif; ?>
        <span><?php echo $block->getName(); ?></span>
    <?php if($_childrenHtml): ?>
        </a>
    <?php endif; ?>
    <a href="#" <?php echo $block->getOutputAttributes();?> class="developertoolbar__highlight-toggle js-developertoolbar__highlight-toggle"><?php echo __('Highlight') ?></a>    
    <?php echo $_childrenHtml; ?>
</li>